### PR TITLE
Changes to allow runtime config of sensor id and gateway mac

### PR DESCRIPTION
**Pull request by lekrom**
Here is a slight mod to allow runtime config of the sensors.

-lekrom

### CODE REVIEW

**Comment by Devilbinder** [comment]
Rather PR this into the dev branch of https://github.com/timmbogner/Farm-Data-Relay-System. So we have central point to work from.
Gave you some feedback in the review section.

**Comment by lekrom** [comment]
Hi @Devilbinder. 
Sounds good, I will do so.
I cant seem to locate the feedback in the review section you spoke of though...
-lekrom

**Comment by Devilbinder** [comment]
Should be here
https://github.com/Devilbinder/Farm-Data-Relay-System/pull/2/files
 It is also showing in the comment chain.

**Pull request closed without merging**
